# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-09 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='state',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Pendiente', 'Pendiente'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=100),
        ),
    ]
